---
title: 'README'
output: 
  md_document:
    variant: markdown_github
---

```{r load_data, include=FALSE, message=FALSE, warning=FALSE}

library(lubridate)

# To translate the month
translate_month_to_english <- function(date) {
  month_names_es <- month.name
  month_names_en <- c("January", "February", "March", "April", "May", "June", 
                      "July", "August", "September", "October", "November", "December")
  
  formatted_date <- format(date, "%B %d, %Y")
  for (i in 1:12) {
    formatted_date <- gsub(month_names_es[i], month_names_en[i], formatted_date)
  }
  return(formatted_date)
}

# Load csv last updated
last_file <- list.files(path = "Last update/", pattern = paste0("^outbreaks"), full.names = TRUE)
rdata_file <- last_file[grepl(".csv$", last_file)]
file_name <- basename(rdata_file)
date_string <- sub(".*_(\\d{2})(\\d{2})(\\d{4}).*", "\\1-\\2-\\3", file_name)
date_obj <- dmy(date_string)

# English format
formatted_date <- translate_month_to_english(date_obj)
formatted_month <- gsub(" ", " ", translate_month_to_english(date_obj))  # Para el mes y año

last_version <- read.csv(rdata_file)

num_countries <- nlevels(factor(last_version$Country))
num_diseases <- nlevels(factor(last_version$icd104n))

```

### **A global dataset of pandemic- and epidemic-prone disease outbreaks**  
### **Torres Munguía, J.A.; Badarau, F.C.; Díaz Pavez, L.R.; Martínez-Zarzoso, I.; & Wacker, Konstantin M.**

Here you can find a new dataset of infectious disease outbreaks collected from the [Disease Outbreak News](https://www.who.int/emergencies/disease-outbreak-news) and the [Coronavirus Dashboard](https://data.who.int/dashboards/covid19) produced by the World Health Organization (WHO). 

**METHODOLOGICAL NOTE:**
The unit of analysis in the database is an **outbreak**, defined as the occurrence of at least one case of a specific disease in a country -or territory- during a particular year. Therefore, a country -or territory- cannot have more than one outbreak of the same disease in the same year, although it may experience outbreaks of different diseases within the same year. A country can only have multiple outbreaks of the same disease if they occur in different years.

Potential applications of the data include combining it with other information sources to explore the relationship between disease outbreaks and factors such as geographical, environmental, globalization, and socioeconomic conditions.

#### About the project ####
The dataset is the result of collaborative work by a team of researchers from the University of Göttingen, the University of Groningen, and the University of Bordeaux. The project was made possible through financial support from the [ENLIGHT network](https://enlight-eu.org/index.php), the German Academic Exchange Service (DAAD), and the Federal Ministry of Education and Research (BMBF) in Germany.

The findings of the first version of the dataset have been published in Springer Nature's Scientific Data.  
[Read the paper by clicking here!](https://www.nature.com/articles/s41597-022-01797-2). Additionally, the data, metadata, and the code to replicate the first version of this dataset are publicly available on Figshare. [You can download them by clicking here!](https://figshare.com/articles/dataset/A_global_dataset_of_pandemic-_and_epidemic-prone_disease_outbreaks/17207183)

#### IMPORTANT NOTE #####
From October 2024, this project is being updated by Dr. Juan Armando Torres Munguía. In case of questions, requests, or collaborations, you can contact me via [GitHub](https://github.com/jatorresmunguia), [X](https://x.com/jtorresmunguia), or [here](https://juan-torresmunguia.netlify.app/contact/). 

The last version of the dataset was updated on `r formatted_date` and contains information on `r nrow(last_version)` **outbreaks**, associated with `r num_diseases` infectious diseases that occurred from January 1996 to `r formatted_month` in `r num_countries` countries and territories worldwide.


